# Generated by Django 3.2 on 2021-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('family', models.CharField(max_length=300)),
                ('kcal', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
